### ISSUE TITLE
Problem with ActionMailer::Base.layout option

### ISSUE THREAD

**Issue by linuxonrails** [smartinez87/exception_notification#120]
I have a layout for the all mailers:

```
  app/views/layouts/mailer.(html.haml|text.haml)
```

with the next option in config/application.rb:

```
  ActionMailer::Base.layout :mailer
```

But exception_notification fail sending error mails:

```
NameError (Could not render layout: undefined local variable or method `mailer' for #<ExceptionNotifier::Notifier:0x00000003c6fd60>):
  actionpack (3.2.11) lib/abstract_controller/layouts.rb:408:in `rescue in _default_layout'
  actionpack (3.2.11) lib/abstract_controller/layouts.rb:405:in `_default_layout'
  actionpack (3.2.11) lib/abstract_controller/layouts.rb:383:in `block in _layout_for_option'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:86:in `call'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:86:in `resolve_layout'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:69:in `block in find_layout'
  actionpack (3.2.11) lib/action_view/lookup_context.rb:228:in `with_layout_format'
  actionpack (3.2.11) lib/action_view/renderer/abstract_renderer.rb:3:in `with_layout_format'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:69:in `find_layout'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:53:in `render_with_layout'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.11) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.11) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:88:in `render'
  exception_notification (2.6.0) lib/exception_notifier/notifier.rb:87:in `block (2 levels) in exception_notification'
  actionmailer (3.2.11) lib/action_mailer/collector.rb:26:in `custom'
  actionpack (3.2.11) lib/abstract_controller/collector.rb:10:in `text'
  exception_notification (2.6.0) lib/exception_notifier/notifier.rb:87:in `block in exception_notification'
  actionmailer (3.2.11) lib/action_mailer/base.rb:697:in `collect_responses_and_parts_order'
  roadie (1.1.3) lib/roadie/action_mailer_extensions.rb:26:in `collect_responses_and_parts_order_with_inline_styles'
  actionmailer (3.2.11) lib/action_mailer/base.rb:648:in `mail'
  roadie (1.1.3) lib/roadie/action_mailer_extensions.rb:20:in `mail_with_inline_styles'
  exception_notification (2.6.0) lib/exception_notifier/notifier.rb:86:in `exception_notification'
  actionpack (3.2.11) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.11) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.11) lib/abstract_controller/rendering.rb:45:in `process'
  actionmailer (3.2.11) lib/action_mailer/base.rb:458:in `process'
  ...
```

**Comment by san650** [comment]
Hi!

I'm doing some bug triage and I would like to know if this bug is still happening on master.

The idea is to close those errors that can't be reproduced or that don't have enough information to reproduce it. I'll revisit this bug in a week and I'll close it if there's no more information. It can be opened again later if necessary.

Thanks!
