### ISSUE TITLE
Net::SMTPFatalError (554 Transaction failed: Missing final '@domain'

### ISSUE THREAD

**Issue by allaire** [smartinez87/exception_notification#132]
Using Amazon SES, I keep getting this error when exception_notification tries to send an email. My other emails are sent normally, I don't know what's wrong.

```
  config.action_mailer.smtp_settings = {
    :address              => 'email-smtp.us-east-1.amazonaws.com',
    :user_name            => 'USERNAME',
    :password             => 'PASS HERE,
    :authentication       => :login,
    :enable_starttls_auto => true
  }
```

```
  # Send email on exceptions
  config.middleware.use ::ExceptionNotifier,
    :email_prefix         => "[Web Exception] ",
    :sender_address       => %w{"Info" <info@lodgem.com>},
    :exception_recipients => %w{dev@lodgem.com}
```

Trace:

```
Completed 500 Internal Server Error in 1044ms
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (1.3ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.6ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.4ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (6.6ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.9ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
  Rendered /home/deployer/apps/web/shared/bundle/ruby/1.9.1/gems/exception_notification-3.0.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (33.1ms)

Sent mail to "Developers", dev@lodgem.com (466ms)

Net::SMTPFatalError (554 Transaction failed: Missing final '@domain'
):
  /usr/local/lib/ruby/1.9.1/net/smtp.rb:948:in `check_response'
  /usr/local/lib/ruby/1.9.1/net/smtp.rb:902:in `data'
  /usr/local/lib/ruby/1.9.1/net/smtp.rb:660:in `block in send_message'
  /usr/local/lib/ruby/1.9.1/net/smtp.rb:849:in `rcptto_list'
  /usr/local/lib/ruby/1.9.1/net/smtp.rb:660:in `send_message'
  mail (2.4.4) lib/mail/network/delivery_methods/smtp.rb:145:in `block in deliver!'
  /usr/local/lib/ruby/1.9.1/net/smtp.rb:520:in `start'
  mail (2.4.4) lib/mail/network/delivery_methods/smtp.rb:144:in `deliver!'
  mail (2.4.4) lib/mail/message.rb:2034:in `do_delivery'
  mail (2.4.4) lib/mail/message.rb:229:in `block in deliver'
  actionmailer (3.2.12) lib/action_mailer/base.rb:415:in `block in deliver_mail'
  activesupport (3.2.12) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.12) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.12) lib/active_support/notifications.rb:123:in `instrument'
  actionmailer (3.2.12) lib/action_mailer/base.rb:413:in `deliver_mail'
  mail (2.4.4) lib/mail/message.rb:229:in `deliver'
  exception_notification (3.0.1) lib/exception_notifier.rb:49:in `rescue in call'
  exception_notification (3.0.1) lib/exception_notifier.rb:41:in `call'
```

Anyone has a clue?

**Comment by san650** [comment]
@allaire Were you able to fix this error?

**Comment by allaire** [comment]
@san650 That's almost 3 years old but AFAIR this was caused by a bad smtp hostname.

**Comment by san650** [comment]
@smartinez87 this issue can be closed
