### ISSUE TITLE
undefined method `new` for ExceptionNotifier:Module

### ISSUE THREAD

**Issue by mcfiredrill** [smartinez87/exception_notification#166]
I'm having trouble precompiling assets with exception_notification enabled.

ruby 2
rails 4.0.0
exception_notifcation 4.0.0.rc1

```
█▓▒░tony@matsuri░▒▓█ ~/src/myapp(master)$ RAILS_ENV=production bundle exec rake assets:precompile
rake aborted!
undefined method `new' for ExceptionNotifier:Module
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.0.0/lib/action_dispatch/middleware/stack.rb:43:in `build'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.0.0/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.0.0/lib/action_dispatch/middleware/stack.rb:118:in `each'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.0.0/lib/action_dispatch/middleware/stack.rb:118:in `inject'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/actionpack-4.0.0/lib/action_dispatch/middleware/stack.rb:118:in `build'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/engine.rb:495:in `app'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/initializable.rb:30:in `run'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/application.rb:215:in `initialize!'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/tony/src/datafruits/config/environment.rb:5:in `<top (required)>'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/application.rb:189:in `require_environment!'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/railties-4.0.0/lib/rails/application.rb:249:in `block in run_tasks_blocks'
/home/tony/.rvm/gems/ruby-2.0.0-p195/gems/sprockets-rails-2.0.0/lib/sprockets/rails/task.rb:54:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by robd** [comment]
https://github.com/smartinez87/exception_notification/commit/abd7ccdec737c050b813f1d1be9626bab8eaaa59#diff-04c6e90faac2675aa89e2176d2eec7d8 removed the upgrade instructions mentioned by @alex-kovshovik. 

The last version where they were available is https://github.com/smartinez87/exception_notification/blob/3b5e1fe1955361882214d74cbfa43e34d9af0c81/README.md#upgrading-to-4x-version
