### ISSUE TITLE
First line of exception missing in slack_notifier?

### ISSUE THREAD

**Issue by aried3r** [smartinez87/exception_notification#352]
My logs show me only the first line of the exception, while the stack trace in Slack is missing exactly this first line, making the stack trace somewhat less useful, since I don't see _where_ the error occurred.

I know this used to work in the past.

Ruby 2.3.1
Rails 4.2.7
exception_notification 4.2

**Comment by aried3r** [comment]
Tried again using 4.2.1. Again it seems the log contains the first line of the exception while Slack contains the remaining lines.

`production.log` (empty lines also in the file!):
```
F, [2016-07-18T10:25:26.171306 #13734] FATAL -- :
RuntimeError (Can't modify frozen hash):
  app/controllers/dummy_controller.rb:12:in `update'


```

Slack:
```
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_set/builder.rb:45:in `[]='
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_set.rb:39:in `write_from_user'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/write.rb:74:in `write_attribute_with_type_cast'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/write.rb:56:in `write_attribute'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods/dirty.rb:97:in `write_attribute'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/attribute_methods.rb:369:in `[]='
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/belongs_to_association.rb:87:in `remove_keys'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/belongs_to_polymorphic_association.rb:18:in `remove_keys'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/belongs_to_association.rb:19:in `replace'
/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/associations/singular_association.rb:17:in `writer'
```

**Comment by aried3r** [comment]
Could it be that the lines are printed "in reverse"? I played around some more with an exception that had a smaller backtrace and noticed that it showed the lines in reverse, the line where the exception occurred was the last line instead of the first.

Think we could change that to have the output the same as in the logs?

**Comment by aried3r** [comment]
I'm closing this as I have moved to another notifier and have no way to reproduce this. Also there's been multiple versions of this gem released in the meantime, especially with fixes to the Slack notifier.
