### ISSUE TITLE
NoMethodError (private method `warn' called for nil:NilClass):

### ISSUE THREAD

**Issue by cheenwe** [smartinez87/exception_notification#404]
log is:
```sh
  raise e if @@testing_mode

      logger.warn "An error occurred when sending a notification using '#{notifier_name}' notifier. #{e.class}: #{e.message}\n#{e.backtrace.join("\n")}"
      false
    end
```

```sh
exception_notification (4.2.2) lib/exception_notifier.rb:116:in `rescue in fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:111:in `fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:55:in `block in notify_exception'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `each'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `notify_exception'
exception_notification (4.2.2) lib/exception_notification/rack.rb:51:in `rescue in call'
exception_notification (4.2.2) lib/exception_notification/rack.rb:41:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
rack-mini-profiler (0.10.7) lib/mini_profiler/profiler.rb:282:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.11.0) lib/puma/configuration.rb:225:in `call'
puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
puma (3.11.0) lib/puma/server.rb:438:in `process_client'
puma (3.11.0) lib/puma/server.rb:302:in `block in run'
puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by cheenwe** [comment]
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
$ rails -v
Rails 5.1.4

**Comment by lazybios** [comment]
I have the same error.

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/40476999-fc6747f2-5f77-11e8-8e56-c5c033d07842.png)
same problem

**Comment by 1c7** [comment]
not sure if this problem relate this repo. it seem like it does

### Env
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Rails 5.2.0
![image](https://user-images.githubusercontent.com/1804755/40477057-1c45cd64-5f78-11e8-9d81-6275f4fa0cd5.png)

**Comment by EmilioCristalli** [comment]
looks like the error you are seeing is coming from this line https://github.com/smartinez87/exception_notification/blob/v4.2.2/lib/exception_notifier.rb#L116
but i'm not being able to reproduce.

How are you guys initializing Exception notification? what notifiers are you using?
Are you setting `Rails.logger` or `ExceptionNotifier.logger` anywhere in your code?

**Comment by EmilioCristalli** [comment]
Going to close this issue since there has been no response for a long time. With only the
information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.

**Comment by fabiensebban** [comment]
For those how are experiencing this issue only in the development environment, you can turn ExceptionNotification off by adding this line in the `config/initializers/exception_notification.rb` file:

```ruby
  config.ignore_if do |exception, options|
    not Rails.env.production?
  end
```
