### ISSUE TITLE
Can't send notification to webhook

### ISSUE THREAD

**Issue by oniksfly** [smartinez87/exception_notification#450]
### Steps to reproduce
`Gemfile`:
```
gem 'httparty'
gem 'exception_notification', '~> 4.3.0'
```

Configuration `config/initializers/exception_notification.rb`:
```
require 'exception_notification/rails'

ExceptionNotification.configure do |config|
  config.add_notifier :webhook, {
    url: 'http://discord-app/integration/rails-logger'
  }
end
```

And I made simple typo in main layout: `csrf_meta_tags` → `csrwef_meta_tags`.

### Expected behavior
I expect request to my notification app.

### Actual behavior
There is no HTTP-request and I've got some entires in rails log:
```
Status: 500 for "/" 

An error occurred when sending a notification using 'webhook' notifier. NoMethodError: undefined method `detect' for #<ActionDispatch::Request::Session:0x00007f9f447bda28>
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request/body.rb:50:in `has_file?'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request/body.rb:52:in `block in has_file?'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request/body.rb:50:in `each'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request/body.rb:50:in `detect'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request/body.rb:50:in `has_file?'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request/body.rb:25:in `multipart?'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request.rb:230:in `setup_raw_request'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty/request.rb:142:in `perform'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty.rb:573:in `perform_request'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty.rb:507:in `post'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/httparty-0.16.3/lib/httparty.rb:624:in `post'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier/webhook_notifier.rb:44:in `block in call'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier/base_notifier.rb:11:in `send_notice'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier/webhook_notifier.rb:43:in `call'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier.rb:117:in `fire_notification'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier.rb:58:in `block in notify_exception'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier.rb:57:in `each'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notifier.rb:57:in `notify_exception'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notification/rack.rb:51:in `rescue in call'
/Users/username/.rvm/gems/ruby-2.5.1@gemset/gems/exception_notification-4.3.0/lib/exception_notification/rack.rb:40:in `call'

... more trace data here and:
  
ActionView::Template::Error (undefined local variable or method `csrwef_meta_tags' for #<#<Class:0x00007f9f432c1ed0>:0x00007f9f44353d48>
Did you mean?  csrf_meta_tags
               csrf_meta_tag):
    2: %html
    3:   %head
    4:     %meta{ name: 'turbolinks-cache-control', content: 'no-cache' }
    5:     = csrwef_meta_tags
    6:     = stylesheet_link_tag    'main', media: 'all', 'data-turbolinks-track' => 'reload'
    7:     = action_cable_meta_tag
    8:     = javascript_include_tag 'main', 'data-turbolinks-track' => 'reload'
  
app/views/layouts/main.html.haml:5:in `_app_views_layouts_main_html_haml___4395026368420467503_70160958755200'
```

When I use email or slack notifiers everything works as expected. 

### System configuration
**Rails version**: 5.1.6

**Ruby version**: 2.5.1

exception_notification version: 4.3.0
httparty version: 0.16.3

**Comment by FLarra** [comment]
Hi @oniksfly, first of all thanks for writing such a good issue report.

The real issue as you also shared in the stacktrace, is in HTTParty gem. There is a fix for that https://github.com/jnunemaker/httparty/pull/626 but until it's merged I suggest using version `0.15.7` of HTTParty or lower in order to be able to send exception notifications through any notifier that uses HTTParty gem.

Please try it out and close the issue if you are good.

**Comment by oniksfly** [comment]
@FLarra thank you! Specifing version of HTTParty solved the issue:

```
gem 'httparty', '0.15.7'
gem 'exception_notification', '~> 4.3.0'
```

**Comment by FLarra** [comment]
Great @oniksfly ! FYI: https://github.com/jnunemaker/httparty/pull/626 was merged too, so you should be good to run the latest HTTParty version & webhooks.
