### ISSUE TITLE
Error on Rails 6.1 for Rails.application.class.parent_name.underscore 

### ISSUE THREAD

**Issue by quorak** [smartinez87/exception_notification#503]
### Steps to reproduce
1. upgrade to Rails 6.1
2. use mattermost exception_notifier (but probably any)
3. throw exception

### Expected behavior
exception gets send to backend

### Actual behavior
```
[2021-01-19T08:11:38.595375 #1]  WARN -- : An error occurred when sending a notification using 'mattermost' notifier.NoMethodError: undefined method `parent_name' for XXX::Application:Class
/usr/local/bundle/gems/railties-6.1.1/lib/rails/railtie.rb:209:in `method_missing'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier/modules/formatter.rb:114:in `rails_app_name'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier/modules/formatter.rb:17:in `initialize'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier/mattermost_notifier.rb:11:in `new'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier/mattermost_notifier.rb:11:in `call'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier.rb:162:in `fire_notification'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier.rb:71:in `block in notify_exception'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier.rb:69:in `each'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notifier.rb:69:in `notify_exception'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:59:in `rescue in call'
/usr/local/bundle/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:48:in `call'
```

### System configuration
**Rails version**: 6.1
**Ruby version**: 2.7.1

**Comment by jmlacroix** [comment]
@quorak you're right, it also happens with a custom notifier.

@smartinez87 any plan on releasing an updated gem version or should I source from master for the time being?

Anyhow, thanks to both of you for your work in this! 🙏

**Comment by jaysonvirissimo** [comment]
Looks like this issue has already been addressed, so can be safely closed now.

cc @smartinez87
