### ISSUE TITLE
webhook notifier.IOError: not opened for reading

### ISSUE THREAD

**Issue by arvindkushwah9** [smartinez87/exception_notification#541]
We have upgraded from ruby 2.7.5  to ruby-3.3.3 and we are getting following error
### ERROR:

W, [2024-08-07T13:00:15.480470 #52435]  WARN -- : An error occurred when sending a notification using 'webhook' notifier.IOError: not opened for reading
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:78:in `read'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:78:in `content_body'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:47:in `block in generate_multipart'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:38:in `each'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:38:in `inject'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:38:in `generate_multipart'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request/body.rb:19:in `call'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request.rb:241:in `setup_raw_request'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty/request.rb:148:in `perform'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty.rb:613:in `perform_request'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty.rb:543:in `post'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/httparty-0.20.0/lib/httparty.rb:650:in `post'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier/webhook_notifier.rb:47:in `block in call'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier/base_notifier.rb:13:in `send_notice'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier/webhook_notifier.rb:46:in `call'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier.rb:161:in `fire_notification'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier.rb:70:in `block in notify_exception'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier.rb:68:in `each'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notifier.rb:68:in `notify_exception'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notification/rack.rb:59:in `rescue in call'
.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/exception_notification-4.5.0/lib/exception_notification/rack.rb:48:in `call'

### System configuration
**Rails version**:
Rails 6.1.4.6
**Ruby version**:
3.3.3

**Other configurations**:

**Comment by arvindkushwah9** [comment]
I found in my investigation this is causing an error:
`options[:body][:environment] = request.filtered_env`
